### ISSUE TITLE
Incluir opção [Excluir, Alterar] na listagem de tarefas abertas por você, sem dono

### ISSUE THREAD

**Issue by rprates** [marianacaramico/StaffFront#25]
![image](https://user-images.githubusercontent.com/13630503/40457882-5a1c9220-5ecf-11e8-9a69-957c2db44284.png)

Incluir um link [Excluir] para permitir que o usuário que abriu uma tarefa, mas que mudou de ideia, remova a tarefa da lista de tarefas disponíveis

**Comment by Anonimy** [comment]
Relacionado ao commit f3cb0e0
